# frozen_string_literal: true

source "https://rubygems.org"

ruby ">= 2.7.0"

gem "thor", "~> 1.3"
gem "terminal-table", "~> 3.0"

group :development do
  gem "rubocop", "~> 1.50"
  gem "rspec", "~> 3.12"
end